### ISSUE TITLE
dhcp does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by shinglerb** [ansible-collections/vyos.vyos#66] opened 2020-07-14 11:09 UTC
##### SUMMARY
When trying to use vyos_l3_interfaces to set an ip address on an interface ansible crashes if an interface in vyos is set to use dhcp.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vyos_l3_interfaces

##### ANSIBLE VERSION

```
ansible 2.11.0.dev0
  config file = None
  configured module search path = ['/home/centos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/centos/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/centos/.local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
```
ansible 2.9.10
  config file = None
  configured module search path = [u'/Users/bshingler/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bshingler/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/bshingler/Library/Python/2.7/bin/ansible
  python version = 2.7.16 (default, Apr 17 2020, 18:29:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

##### OS / ENVIRONMENT

Tried running on both macos catalina and centos 7, target was vyos 4.19.131-amd64-vyos #1 SMP Sun Jul 5 09:43:35 UTC 2020 x86_64

##### STEPS TO REPRODUCE

Have an interface in vyos with a dhcp address:
 interfaces {
     dummy dum1 {
     }
     ethernet eth1 {
         address 192.168.222.207/24
         address dhcp
         mtu 1450
     }
     loopback lo {
     }
 }

```yaml
---
- hosts: vyos
  tasks:
    - name: stick an ip on it
      vyos_l3_interfaces:
        config:
          - name: dum1
            ipv4:
                    - address: 192.168.1.1/24
```

##### EXPECTED RESULTS

Expected dum1 interface to be given the address 192.168.1.1/2

##### ACTUAL RESULTS

Ansible crashed with the following output

```paste below
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a
rapidly changing source of code and can become unstable at any point.
ansible-playbook 2.11.0.dev0
  config file = None
  configured module search path = ['/home/centos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/centos/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/centos/.local/bin/ansible-playbook
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
No config file found; using defaults
host_list declined parsing /home/centos/vyosstuff/inventory as it did not pass its verify_file() method
script declined parsing /home/centos/vyosstuff/inventory as it did not pass its verify_file() method
auto declined parsing /home/centos/vyosstuff/inventory as it did not pass its verify_file() method
Parsed /home/centos/vyosstuff/inventory inventory source with ini plugin
redirecting (type: modules) ansible.builtin.vyos_l3_interfaces to vyos.vyos.vyos_l3_interfaces
[WARNING]: Collection vyos.vyos does not support Ansible version 2.11.0.dev0

PLAYBOOK: site.yml ***********************************************************************************************************************************************************************************
1 plays in site.yml

PLAY [vyos] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************
task path: /home/centos/vyosstuff/site.yml:2
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
[WARNING]: Collection ansible.netcommon does not support Ansible version 2.11.0.dev0
redirecting (type: terminal) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: cliconf) ansible.builtin.vyos to vyos.vyos.vyos
[WARNING]: Ignoring timeout(10) for vyos_facts
<172.25.4.135> ESTABLISH LOCAL CONNECTION FOR USER: centos
<172.25.4.135> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag `"&& mkdir /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664 && echo ansible-tmp-1594724873.4162498-22214-39350126286664="` echo /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.vyos_facts to vyos.vyos.vyos_facts
<vyos> Attempting python interpreter discovery
<172.25.4.135> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<172.25.4.135> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/centos/.ansible/collections/ansible_collections/vyos/vyos/plugins/modules/vyos_facts.py
<172.25.4.135> PUT /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/tmpxak_50_2 TO /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664/AnsiballZ_vyos_facts.py
<172.25.4.135> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664/ /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664/AnsiballZ_vyos_facts.py && sleep 0'
<172.25.4.135> EXEC /bin/sh -c '/usr/bin/python /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664/AnsiballZ_vyos_facts.py && sleep 0'
<172.25.4.135> EXEC /bin/sh -c 'rm -f -r /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724873.4162498-22214-39350126286664/ > /dev/null 2>&1 && sleep 0'
ok: [vyos]
META: ran handlers

TASK [stick an ip on it] *****************************************************************************************************************************************************************************
task path: /home/centos/vyosstuff/site.yml:4
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
[WARNING]: Collection ansible.netcommon does not support Ansible version 2.11.0.dev0
redirecting (type: terminal) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: cliconf) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: action) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: action) ansible.builtin.vyos to vyos.vyos.vyos
<172.25.4.135> ESTABLISH LOCAL CONNECTION FOR USER: centos
<172.25.4.135> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag `"&& mkdir /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974 && echo ansible-tmp-1594724879.4941103-22250-267290698915974="` echo /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.vyos_l3_interfaces to vyos.vyos.vyos_l3_interfaces
Using module file /home/centos/.ansible/collections/ansible_collections/vyos/vyos/plugins/modules/vyos_l3_interfaces.py
<172.25.4.135> PUT /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/tmp2l6vd14_ TO /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py
<172.25.4.135> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/ /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py && sleep 0'
<172.25.4.135> EXEC /bin/sh -c '/usr/bin/python /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py && sleep 0'
<172.25.4.135> EXEC /bin/sh -c 'rm -f -r /home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py", line 102, in <module>
    _ansiballz_main()
  File "/home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.vyos.vyos.plugins.modules.vyos_l3_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_l3_interfaces.py", line 575, in <module>
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_l3_interfaces.py", line 570, in main
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/l3_interfaces/l3_interfaces.py", line 82, in execute_module
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/l3_interfaces/l3_interfaces.py", line 62, in get_l3_interfaces_facts
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/facts.py", line 94, in get_facts
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 128, in get_network_resources_facts
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/l3_interfaces/l3_interfaces.py", line 72, in populate_facts
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/l3_interfaces/l3_interfaces.py", line 100, in render_config
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/l3_interfaces/l3_interfaces.py", line 133, in parse_attribs
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/utils/utils.py", line 218, in get_ip_address_version
  File "/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/compat/ipaddress.py", line 236, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 interface' %
ValueError: u"dhcp'\x1b[m" does not appear to be an IPv4 or IPv6 address
fatal: [vyos]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/centos/.ansible/tmp/ansible-local-22207waqzq0ag/ansible-tmp-1594724879.4941103-22250-267290698915974/AnsiballZ_vyos_l3_interfaces.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vyos.vyos.plugins.modules.vyos_l3_interfaces', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_l3_interfaces.py\", line 575, in <module>\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_l3_interfaces.py\", line 570, in main\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/l3_interfaces/l3_interfaces.py\", line 82, in execute_module\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/l3_interfaces/l3_interfaces.py\", line 62, in get_l3_interfaces_facts\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/facts.py\", line 94, in get_facts\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 128, in get_network_resources_facts\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/l3_interfaces/l3_interfaces.py\", line 72, in populate_facts\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/l3_interfaces/l3_interfaces.py\", line 100, in render_config\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/l3_interfaces/l3_interfaces.py\", line 133, in parse_attribs\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/utils/utils.py\", line 218, in get_ip_address_version\n  File \"/tmp/ansible_vyos_l3_interfaces_payload_ZAxoHw/ansible_vyos_l3_interfaces_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/compat/ipaddress.py\", line 236, in ip_address\n    raise ValueError('%r does not appear to be an IPv4 or IPv6 interface' %\nValueError: u\"dhcp'\\x1b[m\" does not appear to be an IPv4 or IPv6 address\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by mjrider** [comment] 2020-07-15 09:18
because of the  `u"dhcp'\x1b[m"` in the log, i'm guessing it is the same as https://github.com/ansible-collections/vyos.vyos/issues/65

**Comment by shinglerb** [comment] 2020-07-15 10:21
I think you are might be right, in this case it looks as if vyos is sending back ANSI terminal control codes because it thinks ansible is a user with a tty.
Maybe anything that isn't printable/whitespace could be stripped in Cliconf.get_config?

**Comment by Qalthos** [comment] 2020-07-16 17:32
Closing as duplicate of #65

**Closed by Qalthos** 2020-07-16 17:32 UTC
